name: Auto Commit si hay cambios

on:
  schedule:
    - cron: '* * * * *'  # ⏰ Cada minuto (GitHub lo limita a ~5 min en la práctica)
  workflow_dispatch:      # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar usuario Git
        run: |
          git config --global user.name "Angel Sayes"
          git config --global user.email "asayesm@gmail.com"

      - name: Hacer commit y push solo si hay cambios
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "⚠️ No hay cambios para commitear. Saliendo..."
            exit 0
          else
            git commit -m "Auto-commit: $(date)"
            git push
          fi